[project]
name = "pp-ds-monclovalmp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Santiago Velasco", email = "santiagovg2023@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "requests>=2.34.2",
]

[project.scripts]
pp-ds-monclovalmp = "pp_ds_monclovalmp:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
